LOAD DATA
INFILE '/tmp/Static/Inbound/Accomodation/Bonotel/BonotelCountry.csv'
APPEND INTO TABLE STATICDATA_COUNTRY
FIELDS TERMINATED BY ',' optionally enclosed by '"'
(
SUPPLIER_ID CONSTANT 'BONOTEL',
SUPPLIER_NAME CONSTANT 'Bonotel',
COUNTRY_CODE,
COUNTRY_NAME
)







