LOAD DATA 
INFILE '/tmp/Static/Inbound/Accomodation/Bonotel/BonotelHotel.csv'
APPEND INTO TABLE STATICDATA_ACCO
FIELDS TERMINATED BY ',' optionally enclosed by '"'
trailing nullcols
(
SUPPLIER_ID CONSTANT 'BONOTEL',
SUPPLIER_NAME CONSTANT 'Bonotel',
PRODUCT_ID,
PRODUCT_NAME,
A FILLER,
B FILLER CHAR(4000),
C FILLER CHAR(1000),
D FILLER CHAR(1000),
E FILLER,
F FILLER,
ADDR1 BOUNDFILLER,
ADDR2 BOUNDFILLER,
CITY_CODE,
STREET1 ":ADDR1",
STREET2 ":ADDR2",
COUNTRY_CODE,
G FILLER,
H FILLER
)







