LOAD DATA
INFILE '$INBOUNDPATH/$PRODUCT/$SUPPLIER/$NOW/IrctcStationList.txt'
APPEND INTO TABLE STATICDATA_RAIL_STATION 
FIELDS TERMINATED BY ' - '
trailing nullcols
(
SUPPLIER_ID CONSTANT 'IRCTC',
SUPPLIER_NAME CONSTANT 'Irctc',
STATION_NAME,
STATION_ID
)