LOAD DATA 
CHARACTERSET UTF8 
INFILE '/tmp/Static/Inbound/Accomodation/Ati/AtiCountry.txt'
APPEND INTO TABLE STATICDATA_COUNTRY_PROD
FIELDS TERMINATED BY '|' optionally enclosed by '"'
TRAILING NULLCOLS(
SUPPLIER_ID CONSTANT 'ATI',
SUPPLIER_NAME CONSTANT 'Ati',
PRODUCT_ID FILLER,
PRODUCT_NAME FILLER, 
A FILLER CHAR(3000),
ADDR FILLER,
ADDRESS FILLER,
CITY_CODE FILLER,
STATE_NAME FILLER,
COUNTRY_CODE,
D FILLER,
E FILLER,
F FILLER,
Z FILLER,
H FILLER,
I FILLER,
J FILLER,
K FILLER
)







