
LOAD DATA 
INFILE '/tmp/Static/Inbound/Accomodation/Pacto/PactoCountry.csv'
APPEND INTO TABLE STATICDATA_COUNTRY
FIELDS TERMINATED BY ',' optionally enclosed by '"'
(
SUPPLIER_ID CONSTANT 'PACTO',
SUPPLIER_NAME CONSTANT 'Pacto',
COUNTRY_CODE,
COUNTRY_NAME
)







