OPTIONS( SKIP=1)
LOAD DATA 
INFILE '/tmp/Static/Inbound/Accomodation/Desiya/RoomDesc.txt'
APPEND INTO TABLE STATICDATA_ROOMTYPE
FIELDS TERMINATED BY '|' optionally enclosed by '"'
trailing nullcols
(
SUPPLIER_ID CONSTANT 'DESIYA',
SUPPLIER_NAME CONSTANT 'Desiya',
PRODUCT_ID,
ROOMID,
ROOM_NAME,
ROOM_DESCRIPTION CHAR(4000),
MAX_ADULTS,
MAX_CHILD,
MAX_INFANT,
MAX_GUEST_OCCUPANCY,
RoomType_ImagePath FILLER,
ROOMTYPECODE CONSTANT '-',
ROOMTYPECATEGORYID CONSTANT '-'
)








