LOAD DATA 
INFILE '/tmp/Static/Inbound/Accomodation/Dst/DstCity.csv'
APPEND INTO TABLE STATICDATA_CITY
FIELDS TERMINATED BY ',' optionally enclosed by '"'
(
SUPPLIER_ID CONSTANT 'DST ',
SUPPLIER_NAME CONSTANT 'Dst',
CITY_CODE,
CITY_NAME,
COUNTRY_CODE,
COUNTRY_NAME
)







