LOAD DATA
CHARACTERSET WE8ISO8859P1
INFILE '/tmp/Static/Inbound/Accomodation/TravelBullz/TravelBullzHotel.csv'
APPEND INTO TABLE STATICDATA_ACCO 
FIELDS TERMINATED BY ',' optionally enclosed by '"'
trailing nullcols
(
SUPPLIER_ID CONSTANT 'TRAVELBULLZ',
SUPPLIER_NAME CONSTANT 'TravelBullz',
PRODUCT_ID,
PRODUCT_NAME,
STREET1 CHAR(4000),
TELEPHONE_NUMBER,
FAX FILLER,
EMAIL,
WEBSITE CHAR (4000),
COUNTRY_CODE,
COUNTRY_NAME,
CITY_CODE,
CITY_NAME,
F FILLER,
LATITUDE,
LONGITUDE
)








