LOAD DATA
INFILE '/home/oracle/Static/Inbound/Car/ClearCarRental/ClearCarRental_ImportCity.csv'
APPEND INTO TABLE STATICDATA_CAR_CITY 
FIELDS TERMINATED BY ','
trailing nullcols
(
SUPPLIER_ID CONSTANT 'CLEARCARRENTAL',
SUPPLIER_NAME CONSTANT 'ClearCarRental',
ID FILLER,
CITY BOUNDFILLER,
STATE BOUNDFILLER,
CITY_ID ":CITY",
CITY_NAME ":CITY",
STATE_ID ":STATE",
STATE_NAME ":STATE",
COUNTRY_ID CONSTANT 'IN',
COUNTRY_NAME CONSTANT 'India'
)