LOAD DATA
INFILE '/home/oracle/Static/Inbound/Car/ClearCarRental/ClearCarRental_ImportCarTypes.csv'
APPEND INTO TABLE STATICDATA_CAR_TYPES 
FIELDS TERMINATED BY ',' optionally enclosed by '"'
trailing nullcols
(
SUPPLIER_ID CONSTANT 'CLEARCARRENTAL',
SUPPLIER_NAME CONSTANT 'ClearCarRental',
VEHICLE BOUNDFILLER,
SEATING_CAPICITY,
LUGGAGE_CAPICITY,
VEHICLE_TYPE_ID ":VEHICLE",
VEHICLE_TYPE ":VEHICLE"
)