OPTIONS(SKIP=2)
LOAD DATA
INFILE '$INBOUNDPATH/$PRODUCT/$SUPPLIER/Country Names with Country Code.csv'
APPEND INTO TABLE STATICDATA_VISA_COUNTRY
FIELDS TERMINATED BY ','
(
SUPPLIER_ID CONSTANT 'IVA',
SUPPLIER_NAME CONSTANT 'Iva',
SerialNumber FILLER,
COUNTRY_NAME,
COUNTRY_ID
)