LOAD DATA
INFILE '/tmp/Static/Inbound/Accomodation/Rts/RtsHotel.csv'
APPEND INTO TABLE STATICDATA_ACCO
FIELDS TERMINATED BY ','  optionally enclosed by '"'
Trailing nullcols
(
SUPPLIER_ID CONSTANT 'RTS',
SUPPLIER_NAME CONSTANT 'Rts',
A FILLER,
COUNTRY_CODE,
B FILLER,
C FILLER,
CITY_CODE,
D FILLER,
PRODUCT_ID,
PRODUCT_NAME,
STREET1,
E FILLER,
TELEPHONE_NUMBER,
FAX,
G FILLER,
H FILLER
)