LOAD DATA
INFILE '/tmp/Static/Inbound/Accomodation/Rts/RtsCity.csv'
APPEND INTO TABLE STATICDATA_CITY
FIELDS TERMINATED BY ','  optionally enclosed by '"'
Trailing nullcols
(
SUPPLIER_ID CONSTANT 'RTS',
SUPPLIER_NAME CONSTANT 'Rts',
A FILLER,
COUNTRY_CODE,
COUNTRY_NAME,
STATE_CODE,
CITY_CODE,
CITY_NAME,
PRODUCT_ID FILLER,
PRODUCT_NAME FILLER,
ADDRESS FILLER,
E FILLER,
TELEPHONE_NUMBER FILLER,
F FILLER,
G FILLER,
H FILLER
)