
LOAD DATA
INFILE '/tmp/Static/Inbound/Accomodation/Rts/RtsCountry.csv'
APPEND INTO TABLE STATICDATA_COUNTRY
FIELDS TERMINATED BY ','  optionally enclosed by '"'
Trailing nullcols
(
SUPPLIER_ID CONSTANT 'RTS',
SUPPLIER_NAME CONSTANT 'Rts',
A FILLER,
COUNTRY_CODE,
COUNTRY_NAME,
STATE_CODE FILLER,
CITY_CODE FILLER,
CITY_NAME FILLER,
PRODUCT_ID FILLER,
PRODUCT_NAME FILLER,
ADDRESS FILLER,
E FILLER,
TELEPHONE_NUMBER FILLER,
F FILLER,
G FILLER,
H FILLER
)