LOAD DATA
INFILE '/tmp/Static/Inbound/Transfers/Whl/WhlVehicleDetails.csv'
APPEND INTO TABLE STATICDATA_TRANS_VEHICLE_DET
FIELDS TERMINATED BY ',' optionally enclosed by '"'
Trailing nullcols
(
SUPPLIER_ID CONSTANT 'WHL',
SUPPLIER_NAME CONSTANT 'Whl',
VEHICLE_ID,
TYPE FILLER,
NAME FILLER,
CAPACITY FILLER,
DESCRIPTION FILLER CHAR(2000),
BAGGAGES FILLER,
BAGGAGES_TYPE FILLER,
EXTRA_PASSENGERS FILLER
)







