OPTIONS(SKIP=1)
LOAD DATA
INFILE '/tmp/Static/Inbound/Cruise/StarCruise/StarCruise_ImportPort.csv'
APPEND INTO TABLE STATICDATA_CRUISE_PORTS
FIELDS TERMINATED BY ',' optionally enclosed by '"'
trailing nullcols
(
SUPPLIER_ID CONSTANT 'STARCRUISE',
SUPPLIER_NAME CONSTANT 'StarCruise',
PORT_CODE,
PORT_NAME,
UTC_OFFSET BOUNDFILLER,
TENDER_MODE BOUNDFILLER,
COUNTRY_CODE,
STATE_CODE
)