LOAD DATA 
INFILE '/tmp/Static/Inbound/Accomodation/AbreuOnline/AbreuOnlineCountry.csv'
APPEND INTO TABLE STATICDATA_COUNTRY
FIELDS TERMINATED BY ',' optionally enclosed by '"'
(
SUPPLIER_ID CONSTANT 'ABREUONLINE',
SUPPLIER_NAME CONSTANT 'AbreuOnline',
Z FILLER,
Y FILLER,
A FILLER,
ADDRESS FILLER,
B FILLER,
TELEPHONE_NUMBER FILLER ,
C FILLER,
D FILLER,
E FILLER,
COUNTRY_CODE,
COUNTRY_NAME,
F FILLER,
H FILLER,
ISO FILLER
)







