LOAD DATA
INFILE '/tmp/Static/Inbound/Accomodation/AbreuOnline/AbreuOnlineCity.csv'
APPEND INTO TABLE STATICDATA_CITY
FIELDS TERMINATED BY ',' optionally enclosed by '"'
(
SUPPLIER_ID CONSTANT 'ABREUONLINE',
SUPPLIER_NAME CONSTANT 'AbreuOnline',
Z FILLER,
Y FILLER,
A FILLER,
ADDRESS FILLER,
B FILLER,
TELEPHONE_NUMBER FILLER ,
C FILLER,
CITY_CODE,
CITY_NAME,
COUNTRY_CODE,
COUNTRY_NAME,
F FILLER,
H FILLER,
ISO FILLER
)







