
LOAD DATA
INFILE '/tmp/Static/Inbound/Accomodation/Miki/MikiCity.csv'
APPEND INTO TABLE STATICDATA_CITY
FIELDS TERMINATED BY ',' optionally enclosed by '"'
(
SUPPLIER_ID CONSTANT 'MIKI ',
SUPPLIER_NAME CONSTANT 'Miki',
PRODUCT_ID FILLER,
CITY_CODE,
CITY_NAME,
COUNTRY_ BOUNDFILLER,
COUNTRY_CODE "upper(:COUNTRY_)",
COUNTRY_NAME "upper(:COUNTRY_)",
ADDRESS FILLER,
D FILLER,
E FILLER,
F FILLER,
G FILLER,
TELEPHONE_NUMBER FILLER,
H FILLER
)







